name: CI-Tests
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  Code-Style:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: clang-format
      run: sh/run_test_format.sh

  TestSetup:
    runs-on: ubuntu-latest
    outputs:
      chunks: ${{ steps.set-test-ids.outputs.chunks }}
    steps:
      - id: set-test-ids
        run: |
          CHUNKS=$(python -c 'import json; print(json.dumps(list(range(10))))')
          echo "::set-output name=chunks::${CHUNKS}"
          echo "Test chunks: ${CHUNKS}."

  OSXSetup:
    runs-on: ubuntu-latest
    outputs:
      chunks: ${{ steps.set-test-ids.outputs.chunks }}
    steps:
      - id: set-test-ids
        run: |
          CHUNKS=$(python3 -c 'import json; print(json.dumps(list(range(5))))')
          echo "::set-output name=chunks::${CHUNKS}"
          echo "Test chunks: ${CHUNKS}."

  Ubuntu-CMake:
    needs: TestSetup
    timeout-minutes: 150

    name: Ubuntu-CMake-${{ matrix.domain }} (chunk ${{ matrix.chunk }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        domain: [32bit, 64bit, 64bit-noomp]
        chunk: ${{fromJSON(needs.TestSetup.outputs.chunks)}}

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."

    - name: install-lcov
      if: ${{ matrix.domain == '32bit' }}
      run: sudo apt-get update && sudo apt-get install lcov

    - name: install-deps
      run: sudo sh/setup/install_ubuntu_deps.sh

    - name: setup-32bit-domain
      if: ${{ matrix.domain == '32bit' }}
      run: cmake -S . -B build -DSOUFFLE_CODE_COVERAGE=ON

    - name: setup-64bit-domain
      if: ${{ matrix.domain == '64bit' }}
      run: cmake -S . -B build -DSOUFFLE_DOMAIN_64BIT=ON

    - name: setup-64bit-domain-noomp
      if: ${{ matrix.domain == '64bit-noomp' }}
      run: cmake -S . -B build -DSOUFFLE_DOMAIN_64BIT=ON -DSOUFFLE_USE_OPENMP=OFF

    - name: make
      run: cmake --build build -j${JOBS}

    - name: ctest
      run: |
        CHUNKS=$(echo "$(ctest --test-dir build --show-only=json-v1 | jq '.tests | length') 4 ${{ matrix.chunk }}" | python -c 'import json, sys; n_tests, n_chunks, chunk_id = map(int, sys.stdin.readline().split()); d, m = divmod(n_tests, n_chunks); print(f"{chunk_id * d + min(m, chunk_id) + 1},{(chunk_id+1) * d + min(m, chunk_id+1)}")')
        echo "Running tests ${CHUNKS}."
        ctest --test-dir build -I "${CHUNKS}" --output-on-failure --progress -j${JOBS}

    - name: create-coverage-report
      if: ${{ matrix.domain == '32bit' }}
      run: lcov --capture --directory build --output-file coverage.info

    - name: remove-system-files-from-coverage-report
      if: ${{ matrix.domain == '32bit' }}
      run: lcov --remove coverage.info '/usr/*' --output-file coverage.info

    - name: upload-coverage-artifact
      if: ${{ matrix.domain == '32bit' }}
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.domain }}-${{ matrix.chunk }}
        path: coverage.info

  OSX-CMake:
    needs: OSXSetup
    timeout-minutes: 150

    name: OSX-CMake (chunk ${{ matrix.chunk }})

    strategy:
      fail-fast: false
      matrix:
        chunk: ${{fromJSON(needs.OSXSetup.outputs.chunks)}}

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."

    - name: install-deps
      run: sh/setup/install_macos_deps.sh

    - name: setup-32bit-domain
      run: cmake -S . -B build

    - name: make
      run: cmake --build build -j${JOBS}

    - name: ctest
      run: |
        CHUNKS=$(echo "$(ctest --test-dir build --show-only=json-v1 | jq '.tests | length') 5 ${{ matrix.chunk }}" | python3 -c 'import json, sys; n_tests, n_chunks, chunk_id = map(int, sys.stdin.readline().split()); d, m = divmod(n_tests, n_chunks); print(f"{chunk_id * d + min(m, chunk_id) + 1},{(chunk_id+1) * d + min(m, chunk_id+1)}")')
        echo "Running tests ${CHUNKS}"
        ctest --test-dir build -I "${CHUNKS}" --output-on-failure --progress -j${JOBS}
          
  Memory-Check:
    needs: TestSetup
    timeout-minutes: 150

    name: Memory-Check (chunk ${{ matrix.chunk }})

    strategy:
      fail-fast: false
      matrix:
        chunk: ${{fromJSON(needs.TestSetup.outputs.chunks)}}

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."

    - name: install-deps
      run: sudo sh/setup/install_ubuntu_deps.sh

    - name: setup-with-memory-sanitizer
      run: cmake -S . -B build -DSOUFFLE_SANITISE_MEMORY=ON -DSOUFFLE_TEST_EVALUATION=OFF

    - name: make
      run: cmake --build build -j${JOBS}

    - name: ctest
      run: |
        CHUNKS=$(echo "$(ctest --test-dir build --show-only=json-v1 | jq '.tests | length') 4 ${{ matrix.chunk }}" | python -c 'import json, sys; n_tests, n_chunks, chunk_id = map(int, sys.stdin.readline().split()); d, m = divmod(n_tests, n_chunks); print(f"{chunk_id * d + min(m, chunk_id) + 1},{(chunk_id+1) * d + min(m, chunk_id+1)}")')
        echo "Running tests ${CHUNKS}"
        ctest --test-dir build -I "${CHUNKS}" --output-on-failure --progress -j${JOBS}

  Code-Coverage:
    needs: Ubuntu-CMake
    timeout-minutes: 150

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."

    - name: download-coverage-artifacts
      uses: actions/download-artifact@v2

    - name: check-artifacts
      run: |
        echo "List of artifacts:"
        ls

    - name: install-lcov
      run: sudo apt-get update && sudo apt-get install lcov

    - name: merge-coverage-report
      run: lcov $(for i in coverage-*-*/coverage.info; do echo -a $i; done) --output-file coverage.info

    - name: upload-coverage-report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.info
