name: VS-CI-Tests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  CHOCO_CACHE_DIR: "${{ github.workspace }}/choco-cache"

jobs:

  Test-Setup:
     name: Test-Setup
     runs-on: ubuntu-latest
     strategy:
       matrix:
         n-chunks: [4]
     outputs:
       n-chunks: ${{ matrix.n-chunks }}
       chunks: ${{ steps.set-test-ids.outputs.chunks }}
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - id: set-test-ids
         uses: ./.github/actions/set-test-ids
         with:
           n-chunks: ${{ matrix.n-chunks }}

  Windows-CMake-MSVC:
    needs: Test-Setup
    name: Windows-CMake-MSVC (chunk ${{ matrix.chunk }})

    strategy:
       fail-fast: false
       matrix:
         chunk: ${{ fromJSON(needs.Test-Setup.outputs.chunks) }}

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-chocolatey
      with:
        # cache Chocolatey packages to speed-up the deployment.
        path: |
          ${{ env.CHOCO_CACHE_DIR }}
        key: windows-${{ hashFiles('choco-packages.config') }}

    # Use Chocolatey to install binary dependencies.
    - name: Binary Dependencies (Chocolatey)
      run: |
        choco config set cacheLocation ${{ env.CHOCO_CACHE_DIR }}
        choco install choco-packages.config --no-progress --installargs 'ADD_CMAKE_TO_PATH=""System""'

    # Use vcpkg to install devel library dependencies.
    - name: Library Dependencies (vcpkg)
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgGitCommitId: '3a28333d605f92f8659f3af1137324b2d9886101'
        vcpkgTriplet: x64-windows
        vcpkgArguments: 'sqlite3 zlib libffi'

    - name: Create Build Directory
      working-directory: ${{github.workspace}}
      run: mkdir build

    # Run the tests, Visual Studio must be in the environment because cl.exe is required for compiled Souffle.
    - name: Configure Build
      working-directory: ${{github.workspace}}
      run: |
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd

    - name: cmake-test-windows
      uses: ./.github/actions/cmake-test
      with:
         cmake-flags: -G "Visual Studio 16 2019" -A x64 "-DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=/bigobj -DSOUFFLE_DOMAIN_64BIT=ON -DCMAKE_FIND_LIBRARY_PREFIXES=";lib" -DCMAKE_FIND_LIBRARY_SUFFIXES=".lib;.dll" -DSOUFFLE_USE_CURSES=OFF -DSOUFFLE_USE_ZLIB=ON -DCMAKE_FIND_DEBUG_MODE=FALSE -DSOUFFLE_BASH_COMPLETION=OFF
         n-chunks: ${{ needs.Test-Setup.outputs.n-chunks }}
         chunk: ${{ matrix.chunk }}