name: 'cmake-test'
description: 'CMake and CTest'
inputs:
  os:
    description: 'OS'
    required: true
  cmake-flags:
    description: 'CMake flags depending on domain'
    required: true
  chunk:
    chunk: 'Chunk ID'
    required: true
  n-chunks:
    chunk: 'Total number of chunks'
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check-artifacts
      run: |
        echo "Current dir:"
        ls -la
        echo "GitHub dir:"
        ls -la .github/actions/cmake-ctest
      shell: bash

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."
      shell: bash

    - name: setup-domain
      run: cmake -S . -B build ${{ inputs.cmake-flags }}
      shell: bash

    - name: make
      run: cmake --build build -j${JOBS}
      shell: bash

    - name: ctest
      run: |
        CHUNKs=$(echo "$(ctest --test-dir build --show-only=json-v1 | jq '.tests | length') ${{ inputs.n-chunks }} ${{ inputs.chunk }}" | ./.github/actions/cmake-ctest/action.py)
        echo "Running tests ${CHUNKS}."
        ctest --test-dir build -I "${CHUNKS}" --output-on-failure --progress -j${JOBS}
      shell: bash
