name: 'cmake-test'
description: 'CMake and CTest'
inputs:
  os:
    description: 'OS'
    required: true
  cmake-flags:
    description: 'CMake flags depending on domain'
    required: true
  chunk:
    chunk: 'Chunk ID'
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup-env
      run: |
        JOBS=$(nproc || sysctl -n hw.ncpu || echo 2)
        echo "JOBS=${JOBS}" >> $GITHUB_ENV
        echo "Test runner will use ${JOBS} jobs."
      shell: bash

    - name: setup-domain
      run: cmake -S . -B build ${{ inputs.cmake-flags }}
      shell: bash

    - name: make
      run: cmake --build build -j${JOBS}
      shell: bash

    - name: ctest
      run: |
        CHUNKS=$(echo "$(ctest --test-dir build --show-only=json-v1 | jq '.tests | length') 5 ${{ inputs.chunk }}" | python -c 'import json, sys; n_tests, n_chunks, chunk_id = map(int, sys.stdin.readline().split()); d, m = divmod(n_tests, n_chunks); print(f"{chunk_id * d + min(m, chunk_id) + 1},{(chunk_id+1) * d + min(m, chunk_id+1)}")')
        echo "Running tests ${CHUNKS}."
        ctest --test-dir build -I "${CHUNKS}" --output-on-failure --progress -j${JOBS}
      shell: bash
